name: getx_gui
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  get: ^4.6.6
  file_picker: ^4.2.0
  file_selector: ^1.0.0
  flutter_screenutil: ^5.8.4
  url_launcher: ^6.1.14
  msix: ^3.16.1
  get_storage: ^2.1.1
  ansicolor: '>=2.0.1 <3.0.0'
  collection: '>=1.15.0 <2.0.0'
  dart_style: '>=2.0.1 <3.0.0'
  http: '>=0.13.4 <2.0.0'
  intl: '>=0.17.0 <1.0.0'
  meta: '>=1.7.0 <2.0.0'
  path: '>=1.8.0 <2.0.0'
  process_run: '>=0.12.2 <1.0.0'
  pubspec: '>=2.0.1 <3.0.0'
  recase: '>=4.0.0 <5.0.0'
  version: '>=2.0.0 <4.0.0'
  yaml: '>=3.1.0 <4.0.0'
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  video_frame_extractor: ^0.0.3
  flutter_fancy_container: ^0.0.4
  dart_depcheck: ^0.0.1-dev.6+1
  extended_text_field: ^12.1.0
  flutter_test: 
    sdk: flutter

dependency_overrides: 
  ffi: ^2.0.1

flutter: 
  assets: 
    - images/info.svg
    - images/on_board1.svg
    - images/on_board2.svg
    - images/on_board3.svg
    - images/on_board4.svg
    - images/on_board_s.svg
    - images/pen.svg
    - images/prime_whatsapp.svg
    - assets/
  uses-material-design: true

msix_config: 
  display_name: GetX GUI
  publisher_display_name: DharmaTech
  identity_name: dt.getxgui.tech
  msix_version: 1.0.0.0
  logo_path: assets\getx_icon.png
  install_certificate: false
  store: false

